version: '3'

services:

        postgres-db:
                image: postgres
                container_name: postgres-db
                environment:
                        - POSTGRES_USER=guest
                        - POSTGRES_PASSWORD=guest
                        - POSTGRES_DB=blogdbtest
                ports:
                        - "5432:5432"
                volumes:
                        - ./db/BlogDB.sql:/docker-entrypoint-initdb.d/init.sql